services:
  kafka:
    build: .
    restart: always
    networks:
      - kafka-network
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - .env

networks:
  kafka-network:
    external: true
