services:
  notification-service:
    build: .
    container_name: notification-service
    restart: always
    networks:
      - kafka-network
      - app-network
    environment:
      - KAFKA_BROKER=kafka:9092
    env_file:
      - .env
    ports:
      - "8085:8085"

networks:
  kafka-network:
    external: true
