server:
  port: 8085

spring:
  config:
    import: optional:file:.env[.properties]

  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9094}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: >
          main.event.RegistrationEvent:me.pepega.notificationservice.dto.consumer.RegistrationConsume,
          main.event.AdminRequestEvent:me.pepega.notificationservice.dto.consumer.AdminRequestConsume,
          main.event.MayorRequestEvent:me.pepega.notificationservice.dto.consumer.MayorRequestConsume,
          main.event.RequestResponseEvent:me.pepega.notificationservice.dto.consumer.RequestResultConsume,
          main.event.LoginEvent:me.pepega.notificationservice.dto.consumer.LoggedConsume

  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mail:
  main: ${MAIN_MAIL}
app:
  url: ${APP_URL:${DOCKER_APP_URL}}

kind: Application


